### ISSUE TITLE
Reconciler error

### ISSUE THREAD

**Issue by clyang82** [stolostron/multicluster-controlplane#33]
```
E0505 06:41:22.751834       1 controller.go:329]  "msg"="Reconciler error" "error"="ManagedCluster.cluster.open-cluster-management.io \"controlplane1-hosted-mc3\" is invalid: status.conditions: Invalid value: \"null\": status.conditions in body must be of type array: \"null\"" "controller"="clusterinfo-controller" "name"="controlplane1-hosted-mc3" "namespace"="controlplane1-hosted-mc3" "object"={"name":"controlplane1-hosted-mc3","namespace":"controlplane1-hosted-mc3"} "reconcileID"="ac2e9c12-32a9-4942-b3f8-32976189d54d"
```

/assign @skeeey

**Comment by skeeey** [comment]
fixed with https://github.com/stolostron/multicluster-controlplane/pull/41

**Comment by clyang82** [comment]
It works in `multicluster-controlplane` namespace. it still does not work in `default` namespace with the same error described above.
